name: EasyMaintain
version: '${project.version}'
main: mc.plugin.easymaintain.EasyMaintain
api-version: '1.20'

commands:
  em:
    description: Shows list of all available commands
    usage: /<command>